### ISSUE TITLE
新版 Highcharts 的图表的高度 `height` 无法自适应 `container` 

### ISSUE THREAD

**Issue by AAChartModel** [AAChartModel/AAChartKit-Swift#505]
### 使用最新版的 **Highcharts** (v11.4.8) 时, 我遇到一个问题:

* 通过下面这样的 _百分比_ 来设置 `container` 高度:
```css
 #container {
    height: 100%;
} 
```
 **Highcharts** 的图表的高度 `height` 不会自适应.

* 但是如果我是通过类似于设置下面这样的 _固定值_ 来设置 `container` 高度, 
```css
#container {
    height: 200px;
}
```
**Highcharts** 的图表的高度 `height` 就能够自适应了, 这是什么原理?  

之前旧版本的 **Highcharts** 就不会这样, 是不是新版本出 bug 了?
